| 其他維基媒體群組名稱　　　 | 其他維基媒體群組連結 |
| --------------------- | ------------------- |
| 中文小型維基監視群　　　　 | [@cvn_zh_sw](https://t.me/cvn_zh_sw) |
| 文言及各漢語方言維基監視群 | [@cvn_zho](https://t.me/cvn_zho) |
| 閩東語維基百科廣播頻道　　 | [@cdowiki_bulletin](https://t.me/cdowiki_bulletin) |
| 文言維基大典亞洲月頻道　　 | [@wamlzh](https://t.me/wamlzh) |
| 閩東語維基百科群　　　　　 | [@wikipedia_cdo](https://t.me/wikipedia_cdo) |
| 維基共享資源中文群　　　　 | [@wikimedia_commons_zh](https://t.me/wikimedia_commons_zh) |
| 維基大典群　　　　　　　　 | [@wikipedia_lzh](https://t.me/wikipedia_lzh) |
| 滿語維基百科群　　　　　　 | [@wikipedia_mnc](https://t.me/wikipedia_mnc) |
| 粵語維基百科群　　　　　　 | [@wikipedia_yue](https://t.me/wikipedia_yue) |
| 中文維基教科書群　　　　　 | [@wikibooks_zh](https://t.me/wikibooks_zh) |
| 中文維基文庫群　　　　　　 | [@wikisource_zh](https://t.me/wikisource_zh) |
| 中文維基學院群　　　　　　 | [@wikiversity_zh](https://t.me/wikiversity_zh) |
| 中文維基新聞群　　　　　　 | [@wikinews_zh_n](https://t.me/wikinews_zh_n) |
| 中文維基新聞廣播頻道　　　 | [@wikinews_zh_broadcast](https://t.me/wikinews_zh_broadcast) |
| 中文維基導遊群　　　　　　 | [@wikivoyage_zh](https://t.me/wikivoyage_zh) |
| 中文維基語錄群　　　　　　 | [@wikiquote_zh](https://t.me/wikiquote_zh) |
